---
language: python
python: "2.7"
sudo: false
install:
  - pip install ansible==1.9.2
  - '{ echo ''[defaults]''; echo ''roles_path = ../''; } >> ansible.cfg'
script:
  - echo localhost > inventory
  - ansible-playbook -i inventory tests/test.yml --syntax-check
  - ansible-playbook -i inventory tests/test.yml --connection=local --sudo
  - |
    ansible-playbook -i inventory tests/test.yml --connection=local --sudo | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
